-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Aug 29, 2026 at 11:19 AM
-- Server version: 8.4.7
-- PHP Version: 8.3.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `wildlife_emporium`
--

-- --------------------------------------------------------

--
-- Table structure for table `animals`
--

DROP TABLE IF EXISTS `animals`;
CREATE TABLE IF NOT EXISTS `animals` (
  `animalID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `commonName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `scientificName` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `kingdom` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phylum` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `class` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `orderName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `family` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `genus` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `species` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `weight` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `length` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lifespan` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `speed` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `habitat` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `distribution` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `diet` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `behaviour` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `conservationStatus` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `population` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`animalID`)
) ENGINE=MyISAM AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `animals`
--

INSERT INTO `animals` (`animalID`, `commonName`, `scientificName`, `kingdom`, `phylum`, `class`, `orderName`, `family`, `genus`, `species`, `weight`, `length`, `lifespan`, `speed`, `habitat`, `distribution`, `diet`, `behaviour`, `description`, `conservationStatus`, `population`, `image`) VALUES
(1, 'African Lion', 'Panthera leo', 'Animalia', 'Chordata', 'Mammalia', 'Carnivora', 'Felidae', 'Panthera', 'Panthera leo', '150–250 kg', '2.4–3.3 m', '10–14 years', 'Up to 80 km/h', 'Savanna, grassland and woodland', 'Sub-Saharan Africa, including Kenya, Tanzania, Botswana and South Africa.', 'Carnivore', 'Primarily nocturnal. Lions live in social groups called prides and often cooperate when hunting.', 'The African lion is one of the largest members of the cat family. Unlike most other big cats, lions are highly social animals that live together in groups known as prides. Lions are powerful predators that play an important role in their ecosystems and primarily hunt large herbivores.', 'Vulnerable', 'Approximately 20,000–25,000', 'AfricanLion.jpg'),
(2, 'Bengal Tiger', 'Panthera tigris tigris', 'Animalia', 'Chordata', 'Mammalia', 'Carnivora', 'Felidae', 'Panthera', 'Panthera tigris', '90–260 kg', '2.4–3.1 m', '10–15 years', '65 km/h', 'Forests, grasslands and mangrove habitats', 'India, Bangladesh, Bhutan and Nepal', 'Carnivore', 'Solitary and territorial; strong swimmer.', 'The Bengal tiger is a powerful solitary predator distinguished by its orange coat and dark vertical stripes.', 'Endangered', '2,500–3,000', 'bengal_tiger.jpg'),
(3, 'Medium African Elephant', 'Loxodonta africana', 'Animalia', 'Chordata', 'Mammalia', 'Proboscidea', 'Elephantidae', 'Loxodonta', 'Loxodonta africana', '2,700–6,000 kg', '3–4 m', '60–70 years', '40 km/h', 'Savanna, woodland and forest', 'Sub-Saharan Africa', 'Herbivore', 'Highly social; lives in matriarchal family groups.', 'The African elephant is the largest living terrestrial animal and plays an important ecological role in its environment.', 'Endangered', '415,000', 'african_elephant.jpg'),
(4, 'Giant Panda', 'Ailuropoda melanoleuca', 'Animalia', 'Chordata', 'Mammalia', 'Carnivora', 'Ursidae', 'Ailuropoda', 'Ailuropoda melanoleuca', '70–120 kg', '1.2–1.9 m', '15–20 years', '32 km/h', 'Temperate mountain forests', 'Central China', 'Primarily herbivore', 'Mostly solitary; spends much of the day feeding.', 'The giant panda is a bear species adapted to a bamboo-dominated diet and temperate mountain forests.', 'Vulnerable', '1,800+', 'giant_panda.jpg'),
(5, 'Red Fox', 'Vulpes vulpes', 'Animalia', 'Chordata', 'Mammalia', 'Carnivora', 'Canidae', 'Vulpes', 'Vulpes vulpes', '3–14 kg', '0.9–1.1 m', '3–5 years', '50 km/h', 'Forests, grasslands, farmland and urban areas', 'Northern Hemisphere', 'Omnivore', 'Generally solitary and highly adaptable.', 'The red fox is one of the most widely distributed terrestrial mammals and can adapt to many environments.', 'Least Concern', 'Unknown', 'red_fox.jpg'),
(6, 'Giraffe', 'Giraffa camelopardalis', 'Animalia', 'Chordata', 'Mammalia', 'Artiodactyla', 'Giraffidae', 'Giraffa', 'Giraffa camelopardalis', '550–1,200 kg', '4.3–5.7 m', '20–25 years', '60 km/h', 'Savanna, grassland and woodland', 'Sub-Saharan Africa', 'Herbivore', 'Social but loosely structured; often travels in herds.', 'The giraffe is the tallest living terrestrial animal and is recognised by its exceptionally long neck and legs.', 'Vulnerable', '117,000', 'giraffe.jpg'),
(7, 'Bald Eagle', 'Haliaeetus leucocephalus', 'Animalia', 'Chordata', 'Aves', 'Accipitriformes', 'Accipitridae', 'Haliaeetus', 'Haliaeetus leucocephalus', '3–6.3 kg', '0.7–1 m', '20–30 years', '160 km/h', 'Forests near rivers, lakes and coasts', 'North America', 'Carnivore', 'Usually solitary or paired; often nests near water.', 'The bald eagle is a large sea eagle recognised by the white head and tail of mature individuals.', 'Least Concern', '316,000+', 'bald_eagle.jpg'),
(8, 'Emperor Penguin', 'Aptenodytes forsteri', 'Animalia', 'Chordata', 'Aves', 'Sphenisciformes', 'Spheniscidae', 'Aptenodytes', 'Aptenodytes forsteri', '22–45 kg', '1.1–1.3 m', '15–20 years', '9 km/h', 'Antarctic sea ice and surrounding ocean', 'Antarctica', 'Carnivore', 'Highly social; forms large breeding colonies.', 'The emperor penguin is the largest living penguin and breeds during the Antarctic winter.', 'Near Threatened', 'Approx. 600,000', 'emperor_penguin.jpg'),
(9, 'Green Sea Turtle', 'Chelonia mydas', 'Animalia', 'Chordata', 'Reptilia', 'Testudines', 'Cheloniidae', 'Chelonia', 'Chelonia mydas', '65–130 kg', '1–1.2 m', '60–70 years', '35 km/h', 'Tropical and subtropical oceans', 'Tropical and subtropical oceans worldwide', 'Omnivore', 'Migratory; adults often feed in shallow coastal habitats.', 'The green sea turtle is a marine turtle that undertakes long migrations between feeding grounds and nesting beaches.', 'Endangered', 'Unknown', 'green_sea_turtle.jpg'),
(10, 'Komodo Dragon', 'Varanus komodoensis', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Varanidae', 'Varanus', 'Varanus komodoensis', '70–90 kg', '2–3 m', '20–30 years', '20 km/h', 'Dry forests, savanna and scrubland', 'Indonesia', 'Carnivore', 'Mostly solitary; ambushes prey and scavenges.', 'The Komodo dragon is the largest living lizard and an apex predator within its island ecosystem.', 'Endangered', 'Approx. 3,000', 'komodo_dragon.jpg'),
(11, 'Common Hippopotamus', 'Hippopotamus amphibius', 'Animalia', 'Chordata', 'Mammalia', 'Artiodactyla', 'Hippopotamidae', 'Hippopotamus', 'Hippopotamus amphibius', '1,300–3,200 kg', '2.9–5.1 m', '40–50 years', '30 km/h', 'Rivers, lakes, wetlands and surrounding grasslands', 'Sub-Saharan Africa', 'Herbivore', 'Highly territorial in water; spends much of the day submerged and becomes more active at night', 'The common hippopotamus is a large semi-aquatic mammal with a barrel-shaped body, powerful jaws and short legs. Despite its size, it can move quickly on land and is highly territorial around water.', 'Vulnerable', 'Approximately 115,000–130,000', 'common_hippopotamus.jpg'),
(12, 'Polar Bear', 'Ursus maritimus', 'Animalia', 'Chordata', 'Mammalia', 'Carnivora', 'Ursidae', 'Ursus', 'Ursus maritimus', '150–700 kg', '2–2.5 m', '20–30 years', '40 km/h', 'Arctic sea ice, coastal areas and tundra', 'Arctic regions of Canada, Greenland, Norway, Russia and the United States', 'Carnivore', 'Generally solitary; excellent swimmer and relies heavily on sea ice for hunting', 'The polar bear is the largest living land carnivore. Its thick fur and layer of body fat provide insulation in the Arctic environment, while its large paws help it travel across ice and swim.', 'Vulnerable', 'Approximately 22,000–31,000', 'polar_bear.jpg'),
(13, 'Gorilla', 'Gorilla gorilla', 'Animalia', 'Chordata', 'Mammalia', 'Primates', 'Hominidae', 'Gorilla', 'Gorilla gorilla', '70–200 kg', '1.2–1.8 m', '35–40 years', '40 km/h', 'Tropical forests and montane forests', 'Central and western Africa', 'Herbivore', 'Highly social; lives in groups led by a dominant adult male', 'Gorillas are powerful social primates that live in forest habitats. They spend much of their time feeding on vegetation and communicating through vocalisations, gestures and body language.', 'Critically Endangered', 'Approximately 316,000 western lowland gorillas; other populations are much smaller', 'gorilla.jpg'),
(14, 'Kangaroo', 'Macropus giganteus', 'Animalia', 'Chordata', 'Mammalia', 'Diprotodontia', 'Macropodidae', 'Macropus', 'Macropus giganteus', '17–66 kg', '1.8–2.2 m', '8–12 years', '60 km/h', 'Grasslands, woodlands and open forests', 'Eastern and southeastern Australia', 'Herbivore', 'Usually social and often gathers in groups; uses powerful hind legs for rapid movement', 'The eastern grey kangaroo is a large Australian marsupial recognised for its powerful hind legs, long tail and distinctive hopping locomotion. Females raise their young in a pouch.', 'Least Concern', 'Several million', 'kangaroo.jpg'),
(15, 'Blue Jay', 'Cyanocitta cristata', 'Animalia', 'Chordata', 'Aves', 'Passeriformes', 'Corvidae', 'Cyanocitta', 'Cyanocitta cristata', '70–100 g', '25–30 cm', '7 years', '32 km/h', 'Forests, woodland edges, parks and suburban areas', 'Eastern and central North America', 'Omnivore', 'Intelligent and social; known for complex vocalisations and food caching', 'The blue jay is a colourful and intelligent songbird with blue, white and black plumage. It feeds on seeds, nuts, insects and other food and is known for its varied calls.', 'Least Concern', 'Unknown', 'blue_jay.jpg'),
(16, 'Flamingo', 'Phoenicopterus roseus', 'Animalia', 'Chordata', 'Aves', 'Phoenicopteriformes', 'Phoenicopteridae', 'Phoenicopterus', 'Phoenicopterus roseus', '2–4 kg', '1.1–1.5 m', '20–30 years', '60 km/h', 'Shallow lakes, lagoons, mudflats and wetlands', 'Africa, southern Europe and parts of Asia', 'Omnivore', 'Highly social; forms large colonies and feeds in groups', 'The greater flamingo is a large wading bird recognised by its long legs, curved bill and pink plumage. It feeds by filtering small organisms and algae from shallow water.', 'Least Concern', 'Approximately 550,000–680,000 mature individuals', 'flamingo.jpg'),
(17, 'King Cobra', 'Ophiophagus hannah', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Elapidae', 'Ophiophagus', 'Ophiophagus hannah', '6–9 kg', '3–5 m', '20 years', '20 km/h', 'Forests, bamboo stands, mangroves and agricultural areas', 'South and Southeast Asia', 'Carnivore', 'Generally solitary and highly alert; raises its upper body and spreads its hood when threatened', 'The king cobra is the world\'s longest venomous snake. It primarily hunts other snakes and can raise a large portion of its body when threatened.', 'Vulnerable', 'Unknown', 'king_cobra.jpg'),
(18, 'Green Iguana', 'Iguana iguana', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Iguanidae', 'Iguana', 'Iguana iguana', '4–8 kg', '1.2–2 m', '8–12 years', '35 km/h', 'Tropical forests, riverbanks and coastal vegetation', 'Central and South America', 'Herbivore', 'Primarily arboreal; often basks in sunlight and may flee into water when threatened', 'The green iguana is a large arboreal lizard with a long tail, strong claws and a prominent dorsal crest. It feeds mainly on leaves, flowers and other plant material.', 'Least Concern', 'Unknown', 'green_iguana.jpg'),
(19, 'Axolotl', 'Ambystoma mexicanum', 'Animalia', 'Chordata', 'Amphibia', 'Caudata', 'Ambystomatidae', 'Ambystoma', 'Ambystoma mexicanum', '60–110 g', '15–45 cm', '10–15 years', 'Slow-moving', 'Freshwater canals and lakes', 'Xochimilco area of Mexico City, Mexico', 'Carnivore', 'Aquatic and mostly solitary; remains in its larval form throughout adulthood', 'The axolotl is a unique salamander famous for retaining juvenile characteristics throughout its adult life. It can regenerate various body structures and has distinctive external gills.', 'Critically Endangered', 'Fewer than 1,000 estimated in the wild', 'axolotl.jpg'),
(20, 'Common Octopus', 'Octopus vulgaris', 'Animalia', 'Mollusca', 'Cephalopoda', 'Octopoda', 'Octopodidae', 'Octopus', 'Octopus vulgaris', '2–10 kg', 'Up to 1 m', '1–2 years', '40 km/h', 'Rocky reefs, coastal waters and seafloor habitats', 'Tropical and temperate oceans worldwide', 'Carnivore', 'Solitary and highly intelligent; uses camouflage and can release ink when threatened', 'The common octopus is a highly intelligent marine invertebrate with eight arms, sophisticated camouflage abilities and a flexible body. It can change colour and texture to blend into its surroundings.', 'Least Concern', 'Unknown', 'common_octopus.jpg'),
(21, 'Malayan Tapir', 'Tapirus indicus', 'Animalia', 'Chordata', 'Mammalia', 'Perissodactyla', 'Tapiridae', 'Tapirus', 'Tapirus indicus', '250–540 kg', '1.8–2.5 m', '25–30 years', '40 km/h', 'Tropical forests, swamps and riverine habitats', 'Thailand, Myanmar, Malaysia and Sumatra', 'Herbivore', 'Mostly solitary and primarily nocturnal; uses its short trunk to grasp vegetation', 'The Malayan tapir is the largest of the four living tapir species. Its distinctive black-and-white colouring provides camouflage in the dim forests of Southeast Asia.', 'Endangered', 'Unknown', 'malayan_tapir.jpg'),
(22, 'Orangutan', 'Pongo pygmaeus', 'Animalia', 'Chordata', 'Mammalia', 'Primates', 'Hominidae', 'Pongo', 'Pongo pygmaeus', '30–100 kg', '1.2–1.5 m', '35–45 years', 'Up to 5 km/h', 'Lowland tropical rainforests and peat-swamp forests', 'Borneo', 'Omnivore', 'Highly intelligent and predominantly arboreal; generally solitary compared with other great apes', 'The Bornean orangutan is a large reddish-brown great ape that spends most of its life in trees. It uses its long arms to move between branches and feeds heavily on fruit.', 'Critically Endangered', 'Approximately 100,000', 'orangutan.jpg'),
(23, 'Sun Bear', 'Helarctos malayanus', 'Animalia', 'Chordata', 'Mammalia', 'Carnivora', 'Ursidae', 'Helarctos', 'Helarctos malayanus', '25–65 kg', '1.0–1.4 m', '20–25 years', '30 km/h', 'Tropical forests and lowland rainforest', 'Southeast Asia from Myanmar and Thailand to Malaysia, Borneo and Sumatra', 'Omnivore', 'Mostly solitary; excellent climber and often forages in trees', 'The sun bear is the smallest species of bear and is recognised by its short black coat and distinctive golden or orange chest marking. Its long tongue helps it extract honey and insects.', 'Vulnerable', 'Unknown', 'sun_bear.jpg'),
(24, 'Proboscis Monkey', 'Nasalis larvatus', 'Animalia', 'Chordata', 'Mammalia', 'Primates', 'Cercopithecidae', 'Nasalis', 'Nasalis larvatus', '16–22 kg', '55–72 cm', '15–20 years', 'Up to 20 km/h', 'Mangrove forests, riverine forests and coastal wetlands', 'Borneo', 'Herbivore', 'Highly social; lives in groups and is an excellent swimmer', 'The proboscis monkey is an unusual primate found only on the island of Borneo. Males have a prominent elongated nose and large pot belly associated with their specialised diet.', 'Endangered', 'Unknown', 'proboscis_monkey.jpg'),
(25, 'Malayan Flying Fox', 'Pteropus vampyrus', 'Animalia', 'Chordata', 'Mammalia', 'Chiroptera', 'Pteropodidae', 'Pteropus', 'Pteropus vampyrus', '0.6–1.1 kg', '25–32 cm', '15–20 years', 'Up to 40 km/h', 'Tropical forests, mangroves and agricultural areas', 'Southeast Asia including Malaysia, Indonesia, Thailand and the Philippines', 'Herbivore', 'Highly social; forms large colonies and is mainly active at night', 'The Malayan flying fox is one of the largest bats in the world. Despite its name, it is a fruit bat rather than a blood-feeding vampire bat and plays an important role in pollination and seed dispersal.', 'Endangered', 'Unknown', 'malayan_flying_fox.jpg'),
(26, 'Asian Water Monitor', 'Varanus salvator', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Varanidae', 'Varanus', 'Varanus salvator', '20–50 kg', '1.5–2.5 m', '10–15 years', '30 km/h', 'Mangroves, wetlands, rivers and urban waterways', 'South and Southeast Asia', 'Carnivore', 'Excellent swimmer; often searches for prey along waterways and can climb trees', 'The Asian water monitor is a large semi-aquatic lizard with a long muscular tail and powerful claws. It is an adaptable predator capable of living close to human settlements.', 'Least Concern', 'Unknown', 'asian_water_monitor.jpg'),
(27, 'Reticulated Python', 'Malayopython reticulatus', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Pythonidae', 'Malayopython', 'Malayopython reticulatus', 'Up to 75 kg', '3–6 m', '15–20 years', 'Up to 20 km/h', 'Tropical forests, wetlands, grasslands and agricultural areas', 'South and Southeast Asia', 'Carnivore', 'Solitary ambush predator; an excellent swimmer and capable climber', 'The reticulated python is one of the longest snakes in the world. Its intricate patterned scales provide camouflage while it waits for suitable prey to pass nearby.', 'Least Concern', 'Unknown', 'reticulated_python.jpg'),
(28, 'Siamese Crocodile', 'Crocodylus siamensis', 'Animalia', 'Chordata', 'Reptilia', 'Crocodylia', 'Crocodylidae', 'Crocodylus', 'Crocodylus siamensis', '40–120 kg', '2.5–3 m', '35–50 years', '20 km/h', 'Freshwater rivers, lakes, swamps and wetlands', 'Cambodia, Laos, Thailand and parts of Indonesia', 'Carnivore', 'Generally solitary; spends much of its time in or near freshwater', 'The Siamese crocodile is a freshwater crocodilian native to Southeast Asia. It is relatively small compared with many other crocodile species and has a broad snout.', 'Critically Endangered', 'Fewer than 1,000 estimated in the wild', 'siamese_crocodile.jpg'),
(29, 'Giant Clam', 'Tridacna gigas', 'Animalia', 'Mollusca', 'Bivalvia', 'Cardiida', 'Cardiidae', 'Tridacna', 'Tridacna gigas', 'Up to 200 kg', 'Up to 1.2 m', 'Up to 100 years', 'Stationary', 'Shallow tropical coral reefs and clear coastal waters', 'Indo-Pacific region including Southeast Asia', 'Filter feeder', 'Stationary and attached to the reef; relies partly on symbiotic algae for energy', 'The giant clam is the largest living bivalve. It lives in shallow tropical waters and obtains energy both by filtering food from seawater and through symbiotic algae living within its tissues.', 'Vulnerable', 'Unknown', 'giant_clam.jpg'),
(30, 'Whale Shark', 'Rhincodon typus', 'Animalia', 'Chordata', 'Chondrichthyes', 'Orectolobiformes', 'Rhincodontidae', 'Rhincodon', 'Rhincodon typus', 'Up to 21,000 kg', '5–12 m', '70–100 years', '5 km/h', 'Tropical and warm-temperate oceans', 'Tropical oceans worldwide, including waters around Southeast Asia', 'Planktivore', 'Generally solitary; migrates between feeding areas and often gathers where food is abundant', 'The whale shark is the largest living fish. Despite its enormous size, it is a filter feeder that consumes plankton, small fish and other tiny organisms.', 'Endangered', 'Unknown', 'whale_shark.jpg');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
